<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<section id="sma_content_go_pro" class="sma_tab_section">
    <div class="go_pro_container">
        <table class="form-table heading-table" style="margin-bottom:10px">
            <tbody>				
                <tr valign="top">
                    <td>
                        <h1><?php esc_html_e( 'Other Products by zorem', 'woocommerce-shop-manager-admin-bar' ); ?></h1>
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="plugins_section free_plugin_section">
            <div class="single_plugin as-col-4">
                <div class="free_plugin_inner">
                    <div class="paid_plugin_image">
                        <img  src="<?php echo esc_url( woo_shop_manager_admin()->plugin_dir_url() ); ?>assets/images/AST-icon.png">
                        <h3 class="plugin_title">Advanced Shipment Tracking</h3>
                    </div>
                    <div class="paid_plugin_description">
                        
                        <p>Advanced Shipment Tracking (AST) provides all you need to manage and automate the WooCommerce fulfillment workflow.

Easily add tracking information and fulfill orders, keep your customers informed, reduce time spent on post-shipping inquiries and increase overall customer satisfaction.</p>
                        <?php 
                        if ( is_plugin_active( 'woo-advanced-shipment-tracking/woocommerce-advanced-shipment-tracking.php' ) || is_plugin_active( 'ast-pro/ast-pro.php' )) {
                            ?>
                            <button type="button" class="button button button-primary btn_green2">Active</button>
                        <?php } else { ?>
                            <a href="https://wordpress.org/plugins/woo-advanced-shipment-tracking/" class="button button-primary btn_ast2" target="blank"><?php _e('More Info', 'woocommerce'); ?></a>
                        <?php } ?>	
                    </div>
                </div>
            </div>
            <div class="single_plugin as-col-4">
                <div class="free_plugin_inner">
                    <div class="paid_plugin_image">
                        <img  src="<?php echo esc_url( woo_shop_manager_admin()->plugin_dir_url() ); ?>assets/images/trackship_img.png">
                        <h3 class="plugin_title" >TrackShip for WooCommerce</h3>
                    </div>
                    <div class="paid_plugin_description">
                        
                        <p>Take control of your post-shipping workflows, reduce time spent on customer service and provide a superior post-purchase experience to your customers.Beyond automatic shipment tracking, TrackShip brings a branded tracking experience into your store, integrates into your workflow, and takes care of all the touch points with your customers after shipping.</p>
                        <?php 
                        if ( is_plugin_active('trackship-for-woocommerce/trackship-for-woocommerce.php' ) ) {
                            ?>
                            <button type="button" class="button button button-primary btn_green2">Active</button>
                        <?php } else { ?>
                            <a href="https://wordpress.org/plugins/trackship-for-woocommerce/" class="button button-primary btn_ast2" target="blank"><?php esc_html_e('More Info', 'woocommerce'); ?></a>
                        <?php } ?>	
                    </div>
                </div>
            </div>				
            <div class="single_plugin as-col-4">
                <div class="free_plugin_inner">
                    <div class="paid_plugin_image">
                        <img style="margin-right:-6px;" src="<?php echo esc_url( woo_shop_manager_admin()->plugin_dir_url() ); ?>assets/images/smswoo-icon.png">
                        <h3 class="plugin_title">SMS For WooCommerce</h3>
                    </div>
                    <div class="paid_plugin_description">
                       
                        <p>Keep your customers informed by sending them automated SMS text messages with order & delivery updates. You can send SMS notifications to customers when the order status is updated or when the shipment is out for delivery and more…</p>
                        <?php 
                        if ( is_plugin_active('sms-for-woocommerce/sms-for-woocommerce.php' ) ) {
                            ?>
                            <button type="button" class="button button button-primary btn_green2">Active</button>
                        <?php } else { ?>
                            <a href="https://www.zorem.com/product/sms-for-woocommerce/" class="button button-primary btn_ast2" target="blank"><?php esc_html_e('More Info', 'woocommerce'); ?></a>
                        <?php } ?>	
                    </div>
                </div>
            </div>
            <div class="single_plugin as-col-4">
                <div class="free_plugin_inner">
                    <div class="paid_plugin_image">
                        <img src="<?php echo esc_url( woo_shop_manager_admin()->plugin_dir_url() ); ?>assets/images/alp-icon.png">
                        <h3 class="plugin_title">Advanced Local Pickup</h3>
                    </div>
                    <div class="paid_plugin_description">
                        
                        <p>The Advanced Local Pickup (ALP) helps you manage the local pickup orders workflow more conveniently by extending the WooCommerce Local Pickup shipping method. The Pro you set up multiple pickup locations, , split the business hours, apply discounts by pickup location, display local pickup message on the products pages, allow customers to choose pickup location per product, force products to be local pickup only and more…</p>
                        <?php 
                        if ( is_plugin_active( 'advanced-local-pickup-pro/advanced-local-pickup-pro.php' ) ) {
                            ?>
                            <button type="button" class="button button button-primary btn_green2">Active</button>
                        <?php } else { ?>
                            <a href="https://www.zorem.com/product/advanced-local-pickup-for-woocommerce/" class="button button-primary btn_ast2" target="blank"><?php esc_html_e('More Info', 'woocommerce'); ?></a>
                        <?php } ?>	
                    </div>
                </div>
            </div>	
            <div class="single_plugin as-col-4">
                <div class="free_plugin_inner">
                    <div class="paid_plugin_image">
                        <img src="<?php echo esc_url( woo_shop_manager_admin()->plugin_dir_url() ); ?>assets/images/cbr-icon.png">
                        <h3 class="plugin_title">Country Based Restrictions</h3>
                    </div>
                    <div class="paid_plugin_description">
                        
                        <p>The country-based restrictions plugin by zorem works by the WooCommerce Geolocation or the shipping country added by the customer and allows you to restrict products on your store to sell or not to sell to specific countries.</p>
                        <?php 
                        if ( is_plugin_active('country-base-restrictions-pro-addon/country-base-restrictions-pro-addon.php' ) ) {
                            ?>
                            <button type="button" class="button button button-primary btn_green2">Active</button>
                        <?php } else { ?>
                            <a href="https://www.zorem.com/product/country-based-restriction-pro/" class="button button-primary btn_ast2" target="blank"><?php esc_html_e('More Info', 'woocommerce'); ?></a>
                        <?php } ?>	
                    </div>
                </div>
            </div>
            <div class="single_plugin as-col-4">
                <div class="free_plugin_inner">
                    <div class="paid_plugin_image">
                        <img src="<?php echo esc_url( woo_shop_manager_admin()->plugin_dir_url() ); ?>assets/images/AOSM-addons-icon.jpg">
                        <h3 class="plugin_title">Order Status Manager</h3>
                    </div>
                    <div class="paid_plugin_description">
                        
                        <p>The Advanced Order Status Manager allows store owners to manage the WooCommerce orders statuses, create, edit, and delete custom Custom Order Statuses and integrate them into the WooCommerce orders flow.</p>
                        <?php 
                        if ( is_plugin_active('advanced-order-status-manager/advanced-order-status-manager.php' ) ) {
                            ?>
                            <button type="button" class="button button button-primary btn_green2">Active</button>
                        <?php } else { ?>
                            <a href="https://www.zorem.com/product/advanced-order-status-manager/" class="button button-primary btn_ast2" target="blank"><?php esc_html_e('More Info', 'woocommerce'); ?></a>
                        <?php } ?>	
                    </div>
                </div>
            </div>	
    </div>                 
</section>
