<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<div class="zorem-layout__header">
	<h1 class="zorem-layout__header-breadcrumbs"><a href="">Shop Manager Admin </a>
	<span class="dashicons dashicons-arrow-right-alt2"></span><span class="header-breadcrumbs-last"></span></h1>
	<img class="sma_logo_header" src="<?php echo woo_shop_manager_admin()->plugin_dir_url()?>assets/images/SMA-logo.png">
</div>
